---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-service-api
  annotations:
    kubernetes.io/change-cause: 'FirstVersion'
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      app: invoice-server
  strategy:
      type: RollingUpdate
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: invoice-server
    spec:
      containers:
        - image: pitstop/invoiceservice:1.0
          name: invoiceservice
          resources:
            limits:
              memory: 512Mi
              cpu: 250m
          livenessProbe:
              initialDelaySeconds: 20
              periodSeconds: 5
              successThreshold: 1
              failureThreshold: 2
              httpGet:
                path: '/hc'
                port: 80
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production