---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
  annotations:
    kubernetes.io/change-cause: 'FirstVersion'
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: mailserver-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: mailserver-app
    spec:
      containers:
        - image: maildev/maildev:1.1.0
          name: mailserver
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 25
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: '/hc'
              port: 80