---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq-statefulset
  annotations:
    kubernetes.io/change-cause: "FirstVersion"
spec:
  minReadySeconds : 20
  podManagementPolicy: Parallel
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: rabbitmq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3-management-alpine
          resources:
            limits:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 15672
              protocol: TCP
            - containerPort: 5672
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 3
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: '/hc'
              port: 80
          env:
            - name: RABBITMQ_CONFIG_FILE
              value: /etc/pitstop/rabbitmq.conf
          volumeMounts:
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-sample
              mountPath: /etc/pitstop/
      volumes:
        - name: rabbitmq-data
          persistentVolumeClaim: 
            claimName: rabbitmq-data
        - name: rabbitmq-sample
          persistentVolumeClaim: 
            claimName: rabbitmq-sample
          

