---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-server
  annotations:
    kubernetes.io/change-cause: 'FirstVersion'
spec:
  minReadySeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: logserver-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels: 
        app: logserver-app
    spec:
      containers:
        - image: datalust/seq:latest
          name: logserver
          resources:
            limits:
              cpu: 250m
              memory: 512Mi
          ports:
            - containerPort: 5341
              protocol: TCP
            - containerPort: 80
              protocol: TCP
          livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            successThreshold: 1
            failureThreshold: 2
            httpGet:
              path: '/hc'
              port: 80
          env:
            - name: ACCEPT_EULA
              value: "Y" 